# Node.js Function App to Linux on Azure
# Build a Node.js function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - master
    - release

variables:
    # Azure Resource Manager connection created during pipeline creation
    azureSubscription: '12a77424-90ae-4d02-9330-65a782e6c8f7'
    qaFunctionAppName: 'spanilla-service-qa'
    qaEnvironmentName: 'spanilla-service-qa'
    prodFunctionAppName: 'spanilla-service-prod'
    prodEnvironmentName: 'spanilla-service-prod'
    vmImageName: 'ubuntu-latest'

stages:
    - stage: Build
      displayName: Build stage
      jobs:
          - job: Build
            displayName: Build
            pool:
                vmImage: $(vmImageName)

            steps:
                - task: NodeTool@0
                  inputs:
                      versionSpec: '10.x'
                  displayName: 'Install Node.js'

                - script: |
                      yarn
                      yarn test
                  displayName: 'YARN build'

                - task: ArchiveFiles@2
                  displayName: 'Archive files'
                  inputs:
                      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
                      includeRootFolder: false
                      archiveType: zip
                      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
                      replaceExistingArchive: true

                - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
                  artifact: drop

    - stage: DeployQA 
      displayName: Deploy QA
      dependsOn: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      jobs:
          - deployment: Deploy
            displayName: Deploy
            environment: $(qaEnvironmentName)
            pool:
                vmImage: $(vmImageName)
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - task: AzureFunctionApp@1
                              displayName: 'Azure Functions App Deploy: spanilla-service-qa'
                              inputs:
                                  azureSubscription: '$(azureSubscription)'
                                  appType: functionAppLinux
                                  appName: $(qaFunctionAppName)
                                  package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                                
    - stage: DeployProd 
      displayName: Deploy Prod
      dependsOn: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
      jobs:
          - deployment: Deploy
            displayName: Deploy
            environment: $(prodEnvironmentName)
            pool:
                vmImage: $(vmImageName)
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - task: AzureFunctionApp@1
                              displayName: 'Azure Functions App Deploy: spanilla-service-prod'
                              inputs:
                                  azureSubscription: '$(azureSubscription)'
                                  appType: functionAppLinux
                                  appName: $(prodFunctionAppName)
                                  package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
